# this is a mockup file to illustrate future AppStack concepts 
apiVersion: experimental.kontinue.io/v1
kind: Workload
metadata:
  name: online-store-frontend
  labels:
    app.kubernetes.io/name: online-store-frontend
    app.tanzu.vmware.com/workload-type: web
  spec:
    git:
      url: https://github.com/dektlong/store-frontend-ux.git
      ref:
          branch: main