#@ load("@ytt:data", "data")
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: #@ data.values.artifactId + "-routes"
spec:
  service: 
    name: #@ data.values.artifactId + "-service"
  routes:
    - predicates:
        - #@ "Path=/api/" + data.values.apiGroups[1] + "/login"
        - Method=GET
      filters:
        - #@ "RedirectTo=302" + ", /" + data.values.apiGroups[0]
      ssoEnabled: true
      order: 0
      tags:
        - #@ data.values.apiGroups[1]
      title: "SSO protected api for write functionality"
      description: "SSO protected api for write/delete/update interactions with the frontend service"
    - predicates:
        - #@ "Path=/" + data.values.apiGroups[0]
        - Method=GET
      order: 1000
      tags:
        - #@ data.values.apiGroups[0]    
      title: "open api for read-only functionality"
      description: "open api for read only interactions with the front end service"
