apiVersion: skaffold/v2beta10
kind: Config

build:
  local:
    concurrency: 2
  artifacts:
    - image: my-dev-registry.example.com/{{app-name}}
      custom:
        buildCommand: |
          npm run build && ./gradlew :{{app-name}}:npm_ci
        dependencies:
          paths:
            - ../../src/**
            - ../../build.gradle
deploy:
  kubectl:
    manifests:	# 	the Kubernetes yaml or json manifests.
    - "../*.yaml"
    flags:
      apply:
        - --force  
