apiVersion: skaffold/v2beta10
kind: Config

build:
  local:
    concurrency: 2
  artifacts:
    - image: my-dev-registry.example.com/app-name
      custom:
        buildCommand: |
          ./gradlew :bootBuildImage --imageName="$IMAGE" && \
          if [ "$PUSH_IMAGE" = "true" ]; then docker push "$IMAGE"; fi
        dependencies:
          paths:
            - src/main/**
            - ../../build.gradle
            - ../../settings.gradle
deploy:
  kubectl:
    manifests:	# 	the Kubernetes yaml or json manifests.
    - "../*.yaml"
    flags:
      apply:
        - --force  
