apiVersion: kontinue.io/v1alpha1
kind: Workload
metadata:
  name: app-name
  labels:
    app.tanzu.vmware.com/workload-type: web

spec:

  git:
    url: git-repo
    ref: {branch: main}
    
resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m
