apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{appName}}
spec:
  selector:
    matchLabels:
      app: {{appName}}
  template:
    metadata:
      labels:
        app: {{appName}}
    spec:
      imagePullSecrets: 
      - name: imagereg-secret
      containers:
        - name: {{appName}}
          image: {{appName}}:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{appName}}-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{appName}}


